setwd("C:/Users/Tycoon/Desktop/Coursera/Exploratory Data/Assgn#01/exdata-data-household_power_consumption")
list.files()
data<- read.csv("household_power_consumption.txt", sep=";", na.strings="?", stringsAsFactor=F)
library(dplyr)
data<- tbl_df(data)
class(data$Date)
library(lubridate)
data$Date<- dmy(data$Date)
data$Date<- as.character(data$Date)
new_data<- subset(data, Date == "2007-02-01" | Date == "2007-02-02")
png("plot1.png", width=480, height=480)
with(new_data, hist(Global_active_power, xlab="Global Active Power (Kilowatts)", main="Global Active Power", col="red"))
dev.off()
