setwd("C:/Users/Tycoon/Desktop/Coursera/Exploratory Data/Assgn#01/exdata-data-household_power_consumption")
list.files()
data<- read.csv("household_power_consumption.txt", sep=";", na.strings="?", stringsAsFactor=F)
library(dplyr)
data<- tbl_df(data)
library(lubridate)
data$Date<- dmy(data$Date)
data$Date<- as.character(data$Date)
new_data<- subset(data, Date == "2007-02-01" | Date == "2007-02-02")
new_data<- mutate(new_data, datetime= paste(Date, Time))
new_data$datetime<- ymd_hms(new_data$datetime)
png("plot2.png", width=480, height=480)
with(new_data, plot(datetime, Global_active_power, type="l", ylab="Global Active Power (Kilowatts)", xlab=""))
dev.off()
