setwd("C:/Users/Tycoon/Desktop/Coursera/Exploratory Data/Assgn#01/exdata-data-household_power_consumption")
list.files()
data<- read.csv("household_power_consumption.txt", sep=";", na.strings="?", stringsAsFactor=F)
library(dplyr)
data<- tbl_df(data)
class(data$Date)
library(lubridate)
data$Date<- dmy(data$Date)
data$Date<- as.character(data$Date)
new_data<- subset(data, Date == "2007-02-01" | Date == "2007-02-02")
new_data<- mutate(new_data, datetime= paste(Date, Time))
new_data$datetime<- ymd_hms(new_data$datetime)
png("plot4.png", width=480, height=480)
par(mfrow=c(2,2), mar=c(4,4,2,1))
with(new_data, plot(datetime, Global_active_power, type="l", ylab="Global Active Power", xlab=""))
with(new_data, plot(datetime, Voltage, type="l", ylab="Voltage", xlab="datetime"))
with(new_data, plot(datetime, Sub_metering_1, ylab="Energy Sub metering", xlab="", type="l"))
with(new_data, lines(datetime, Sub_metering_2, col="red"))
with(new_data, lines(datetime, Sub_metering_3, col="blue"))
with(new_data, legend('topright', c("Sub_metering_1","Sub_metering_2", "Sub_metering_3"), lwd=1, lty=1, col=c("black", "red", "blue"), bty="n"))
with(new_data, plot(datetime, Global_reactive_power, type="l"))
dev.off()
